// <auto-generated />
using Google.Keep;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Practice.Migrations
{
    [DbContext(typeof(GoogleContext))]
    [Migration("20180921042746_Note")]
    partial class Note
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.3-rtm-32065")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Google.Keep.Keep", b =>
                {
                    b.Property<int>("KeepId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Text");

                    b.Property<string>("Title")
                        .IsRequired();

                    b.HasKey("KeepId");

                    b.ToTable("Google");
                });

            modelBuilder.Entity("Google.Keep.LabelNote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("KeepId");

                    b.Property<string>("items");

                    b.HasKey("Id");

                    b.HasIndex("KeepId");

                    b.ToTable("Label");
                });

            modelBuilder.Entity("Google.Keep.LabelNote", b =>
                {
                    b.HasOne("Google.Keep.Keep")
                        .WithMany("Lable")
                        .HasForeignKey("KeepId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
